### ISSUE TITLE
You should consider to tell people how to ugrade from radix 7.3.x rc4

### ISSUE THREAD

**Issue by horvan** [radixtheme/radix#13]
I ran into problems while upgrading a subtheme that was initially created with radix 7.3 

The following thread solved the problems:

http://stackoverflow.com/questions/32490328/gulp-autoprefixer-throwing-referenceerror-promise-is-not-defined

**Comment by arshad** [comment]
Yes. We are working on documentation.

**Comment by arshad** [comment]
Done. See http://www.radixtheme.org/articles/update-rc4-to-3/
