### ISSUE TITLE
Kits out of radix theme

### ISSUE THREAD

**Issue by MathAndrews** [radixtheme/radix#2]
Hi,

I made my own theme, which is a subtheme of radix.

From my theme, i made a kit to create subtheme of my own theme.

I don't want to put my kit in radix kits directory because it's not part of radix, and I don't want it to be erase if I update Radix.
So I put my kit in my theme and run the drush command:
```
drush radix "Subtheme name" --kit=../../mytheme/kits/default --machine_name=subtheme_name --description="Description for my subtheme"
```

But it cannot "rename" the info file because it concat the kit parameter with '.info':
```
../../mytheme/kits/default.info
```
This file doesn't exist.

The file path should be:
```
../mytheme/kits/default/default.info
```

I may not use the kit parameter as it meant to be.

Best regards,

Mathieu

**Comment by arshad** [comment]
I'll take a look at this again tomorrow but can you host your kit on Github? Radix can pick up kit from external sources.

See https://github.com/arshad/radix-kit-default

Then:

```
drush radix "THEME NAME" --kit=https://github.com/arshad/radix-kit-default/archive/master.zip
```

Note that your kit needs to be named as follows: radix-kit-KITNAME.

**Comment by MathAndrews** [comment]
Ok, I will try the to host it on a git repository.

I notice that in fact, it look to the info file of the kit, the path is defined from the new subtheme folder, but if the subtheme is created in another folder (using the destination parameters) the kit will not be found neither.

As the info file is move in the new subtheme folder, you can rename the info file in the new subtheme folder instead of using the one from the kit.

I'm not sure if i'm clear.

**Comment by arshad** [comment]
Marking this as closed. Feel free to reopen if you have any question.
