### ISSUE TITLE
guard livereload in default kit

### ISSUE THREAD

**Issue by horvan** [radixtheme/radix#3]
Hi 

I like radix a lot but I can't figure out how to set up guard-liverload with bundler and radix. Although I have installed all these fancy gems need for livelreoading. is ist possible to make a guard-liverelaod supporting kit for radix?

**Comment by arshad** [comment]
Thanks for the report. I'll see if I can get Gulp + Livereload for Radix this weekend. I'll update this thread.

**Comment by arshad** [comment]
@horvan We've added Gulp + BrowserSync for Radix. BrowserSync is like livereload but with a lot more features. See http://www.browsersync.io

Can you help us test it? I'm adding instructions below on how to add Gulp + BrowserSync to an existing Radix subtheme.

### Step 1
Copy the following files from **https://github.com/radixtheme/radix/blob/7.x-3.x/kits/default** to the root of your Radix subtheme.

1. https://github.com/radixtheme/radix/blob/7.x-3.x/kits/default/gulpfile.js
2. https://github.com/radixtheme/radix/blob/7.x-3.x/kits/default/package.json
3. https://github.com/radixtheme/radix/blob/7.x-3.x/kits/default/config.json

### Step 2
Update the browserSyncProxy in **config.json**.

### Step 3
Run `npm install` from the root of your Radix subtheme.

### Step 4
Run `gulp` to watch for changes.

Gulp should detect changes in your Sass, compile it and automatically reload all your browsers.

Please note when using browserSync, you need to test your website at `http://localhost:3000`.

### How to view my website on several devices?

When you run `gulp` you should see local and external access urls as follows:

![1__gulp__node_](https://cloud.githubusercontent.com/assets/124599/7800072/b1cbd8f4-0320-11e5-8ae4-4d935c39d2de.png)

Use the external address to view your site on other devices.

**Comment by horvan** [comment]
After insalling and compiling by npm install gulp is not working 

'''Shell
 npm install
npm WARN package.json Radix@3.0.0 No repository field.
npm WARN package.json Radix@3.0.0 No README data
npm WARN package.json Radix@3.0.0 No license field.
npm WARN optional dep failed, continuing fsevents@0.3.6
 
> ws@0.5.0 install /var/www/html/sites/all/themes/guild/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/www/html/sites/all/themes/guild/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/var/www/html/sites/all/themes/guild/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
 
> spawn-sync@1.0.11 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

|
> spawn-sync@1.0.11 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.11 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.11 postinstall /var/www/html/sites/all/themes/guild/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> ws@0.4.31 install /var/www/html/sites/all/themes/guild/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/www/html/sites/all/themes/guild/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/var/www/html/sites/all/themes/guild/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'

> node-sass@3.1.2 install /var/www/html/sites/all/themes/guild/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /var/www/html/sites/all/themes/guild/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node

> optipng-bin@2.0.4 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> jpegtran-bin@2.0.2 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@2.0.1 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully


> pngcrush-bin@3.0.0 postinstall /var/www/html/sites/all/themes/guild/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin
> node lib/install.js

  ✔ pngcrush pre-build test passed successfully

> node-sass@3.1.2 postinstall /var/www/html/sites/all/themes/guild/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /var/www/html/sites/all/themes/guild/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> Radix@3.0.0 postinstall /var/www/html/sites/all/themes/guild
> find node_modules/ -name '*.info' -type f -delete

gulp-rename@1.2.2 node_modules/gulp-rename

gulp-compass@2.1.0 node_modules/gulp-compass
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── which@1.1.1 (is-absolute@0.1.7)
└── gulp-util@3.0.5 (object-assign@2.0.0, array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, chalk@1.0.0, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, dateformat@1.0.11)

gulp-shell@0.4.1 node_modules/gulp-shell
├── async@0.9.2
├── lodash@3.5.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── gulp-util@3.0.5 (object-assign@2.0.0, array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, chalk@1.0.0, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, dateformat@1.0.11)

gulp-livereload@3.8.0 node_modules/gulp-livereload
├── debug@2.2.0 (ms@0.7.1)
├── event-stream@3.3.1 (duplexer@0.1.1, from@0.1.3, stream-combiner@0.0.4, pause-stream@0.0.11, map-stream@0.1.0, split@0.3.3, through@2.3.7)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── lodash.assign@3.2.0 (lodash._baseassign@3.2.0, lodash._createassigner@3.1.1, lodash.keys@3.1.1)
├── gulp-util@3.0.5 (object-assign@2.0.0, array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, chalk@1.0.0, through2@0.6.5, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, dateformat@1.0.11)
└── tiny-lr@0.1.5 (parseurl@1.3.0, qs@2.2.5, livereload-js@2.2.2, debug@2.0.0, faye-websocket@0.7.3, body-parser@1.8.4)

gulp@3.8.11 node_modules/gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── semver@4.3.5
├── tildify@1.0.0 (user-home@1.1.1)
├── v8flags@2.0.5 (user-home@1.1.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── gulp-util@3.0.5 (object-assign@2.0.0, array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, chalk@1.0.0, through2@0.6.5, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.7, through2@0.6.5, mkdirp@0.5.1, defaults@1.0.2, vinyl@0.4.6, strip-bom@1.0.0, glob-stream@3.1.18, glob-watcher@0.0.6)

browser-sync@2.7.6 node_modules/browser-sync
├── async-each-series@0.1.1
├── longest@1.0.1
├── query-string@2.2.0
├── emitter-steward@0.0.1
├── ucfirst@0.0.1
├── opn@1.0.2
├── dev-ip@1.0.1
├── ua-parser-js@0.7.7
├── browser-sync-client@2.0.2
├── immutable@3.7.3
├── lodash@3.9.3
├── pad-left@1.0.2 (repeat-string@1.5.2)
├── portscanner@1.0.0 (async@0.1.15)
├── easy-extender@2.3.1 (lodash@2.4.2)
├── localtunnel@1.5.1 (debug@0.7.4, request@2.11.4, optimist@0.3.4)
├── connect@3.3.5 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.3, finalhandler@0.3.4)
├── foxy@11.0.0 (cookie@0.1.3, http-proxy@1.11.1, lodash.merge@3.3.1)
├── resp-modifier@3.1.2 (minimatch@2.0.8)
├── eazy-logger@2.1.2 (opt-merger@1.1.0, tfunk@3.0.1)
├── serve-index@1.6.4 (escape-html@1.0.1, parseurl@1.3.0, batch@0.5.2, debug@2.2.0, http-errors@1.3.1, accepts@1.2.7, mime-types@2.0.12)
├── serve-static@1.9.3 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, send@0.12.3)
├── chokidar@1.0.2 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0)
├── meow@3.1.0 (object-assign@2.0.0, minimist@1.1.1, camelcase-keys@1.0.0, indent-string@1.2.1)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.1.6)
├── browser-sync-ui@0.5.9 (connect-history-api-fallback@0.0.5, angular-touch@1.4.0, angular-sanitize@1.4.0, angular-route@1.4.0, angular@1.4.0, stream-throttle@0.1.3, weinre@2.0.0-pre-I0Z7U9OV)
└── socket.io@1.3.5 (has-binary-data@0.1.3, debug@2.1.0, socket.io-parser@2.2.4, socket.io-adapter@0.3.1, engine.io@1.5.1, socket.io-client@1.3.5)

gulp-imagemin@2.2.1 node_modules/gulp-imagemin
├── object-assign@2.0.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── through2-concurrent@0.3.1 (through2@0.6.5)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
├── gulp-util@3.0.5 (array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, through2@0.6.5, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, dateformat@1.0.11)
└── imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, through2@0.6.5, buffer-to-vinyl@1.0.0, concat-stream@1.4.8, meow@3.1.0, stream-combiner2@1.0.2, imagemin-svgo@4.1.2, vinyl-fs@1.0.0, imagemin-optipng@4.2.0, imagemin-jpegtran@4.1.0, imagemin-gifsicle@4.1.0)

imagemin-pngcrush@4.1.0 node_modules/imagemin-pngcrush
├── is-png@1.0.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── exec-buffer@2.0.1 (tempfile@1.1.1, rimraf@2.3.4)
└── pngcrush-bin@3.0.0 (logalot@2.1.0, bin-build@2.1.1, bin-wrapper@3.0.1)

gulp-sass@2.0.1 node_modules/gulp-sass
├── object-assign@2.0.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.5 (array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, chalk@1.0.0, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, dateformat@1.0.11)
└── node-sass@3.1.2 (get-stdin@4.0.1, async-foreach@0.1.3, nan@1.8.4, mkdirp@0.5.1, chalk@1.0.0, glob@5.0.10, meow@3.1.0, gaze@0.5.1, request@2.56.0, pangyp@2.2.0, npmconf@2.1.2, sass-graph@2.0.0)
➜  guild  gulp
zsh: command not found: gulp
➜  guild  gulp
zsh: command not found: gulp
'''

**Comment by horvan** [comment]
after
```shell

 npm install -g gulp ;cd $themefolder i got the following

 gulp      
[20:10:28] Using gulpfile /var/www/html/sites/all/themes/guild/gulpfile.js
[20:10:28] Starting 'sass'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: You need to have Ruby and Compass installed and in your system PATH for this task to work.
➜  guild  echo $PATH
/home/drupal/.composer/vendor/bin:/home/drupal/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
➜  guild  
```

**Comment by arshad** [comment]
Yep so we're still using compass. You still need to have it install.

`
cd $themefolder;
bundle install;
npm install
`
then `gulp`

**Comment by horvan** [comment]
installing the bindle did the job so everything seems to be fine

**Comment by arshad** [comment]
Browsersync working?

On Sun, May 31, 2015 at 12:36 AM Horvan <notifications@github.com> wrote:

> installing the bindle did the job so everything seems to be fine
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radixtheme/radix/issues/3#issuecomment-107082253>.
>
-- 
Sent from my iPhone

**Comment by horvan** [comment]
Yes but not without setting up gulp manually. It may be confusing if there is no documentation no this. In short terms If the user is able to set it up correctly browsersync works like a charm :-)

By the way. I have seen some other bugs while testing. Where do you love to track issues. In drupal.orgs issue queqe or here on github?

**Comment by arshad** [comment]
Yeah gulp is still available in the dev version. We still have to write documentation for that. We wanted to test it here first.

Yes, Github works. You can create issues here.

**Comment by horvan** [comment]
Thanks for your support.
