### ISSUE TITLE
browser sync is not working for drush cc all 

### ISSUE THREAD

**Issue by horvan** [radixtheme/radix#4]
It seams browser symc does not work with drush cc. Is it possible to add support for that?

**Comment by arshad** [comment]
Yep. Let me check. Might be something with Drupal and npm files.

**Comment by arshad** [comment]
Can you check if you have the following line in your package.json?

https://github.com/radixtheme/radix/blob/7.x-3.x/kits/default/package.json#L6

**Comment by horvan** [comment]
The line is there for shure, because i just did a fresh setup witth a git clone.

**Comment by arshad** [comment]
Can you try run `npm run postinstall` in your $themeroot then `drush cc all`?

**Comment by horvan** [comment]
```shell
  guild  npm run postinstall

> Radix@3.0.0 postinstall /var/www/html/sites/all/themes/guild
> find node_modules/ -name '*.info' -type f -delete

```

**Comment by arshad** [comment]
Does `drush cc all` works after this? What's the error/output?

**Comment by horvan** [comment]
there is no reload in the browser window just as before

**Comment by arshad** [comment]
Are you on the local url provided by browsersync? http://localhost:3000. (The port might be different)

**Comment by horvan** [comment]
oh uh I just seen in the gulp.js file that you just watching scss files.  

For this mime-type it seems to work but drush cc all does notinvoke browsersync if it is executed from the command line.

 Is there a way to watch the .tpl.php in the themes subfolders and the template.php file in the subtheme folder,  too?

**Comment by arshad** [comment]
Yep. So you can add the following line right after https://github.com/radixtheme/radix/blob/7.x-3.x/kits/default/gulpfile.js#L33

`gulp.watch('templates/**/*').on('change', browserSync.reload);`

**Comment by horvan** [comment]
since you added browsersync it is working like a charm
