### ISSUE TITLE
user menu missing

### ISSUE THREAD

**Issue by horvan** [radixtheme/radix#7]
in radix default kits page.tpl there is no secondary menu yet. is it possible to fix this?

**Comment by arshad** [comment]
We replaced the secondary menu with the search form in the navbar in recent versions. But it's quite easy to add back. Here's how:

In template.php, add the following code in `hook_preprocess_page`:

``` php
<?php
/**
 * Implements template_preprocess_page().
 */
function THEME_preprocess_page(&$variables) {
  // Add the user menu to the template.
  $user_menu_data = menu_build_tree('user-menu', array(
    'min_depth' => 1,
    'max_depth' => 2,
  ));
  $variables['user_menu'] = menu_tree_output($user_menu_data);
  $variables['user_menu']['#theme_wrappers'] = array();
}
?>
```

Then in your page.tpl.php, render the menu as follows:

```html
<?php if ($user_menu): ?>
  <ul class="nav user-nav">
    <?php print render($user_menu); ?>
  </ul>
<?php endif; ?>
```

**Comment by barraponto** [comment]
@arshad should we document that somewhere?

**Comment by arshad** [comment]
I'm not sure where this would go in the documentation: https://github.com/radixtheme/documentation

Maybe a separate page for tips and tricks? Or just guides?

**Comment by barraponto** [comment]
I'd add it to a FAQ or Common Practices section (like http://doc.scrapy.org/en/latest/topics/practices.html)

**Comment by horvan** [comment]
That's a great choice
